2019-03-28 22:00:26,876 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-03-28 22:01:19,817 ERROR: Exception on /edit_profile [POST] [in /Users/Mark/anaconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Mark/Documents/GitHub/Flasky/app/routes.py", line 74, in edit_profile
    db.session.commit()
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1023, in commit
    self.transaction.commit()
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 487, in commit
    self._prepare_impl()
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 466, in _prepare_impl
    self.session.flush()
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2436, in flush
    self._flush(objects)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2574, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2534, in _flush
    flush_context.execute()
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 976, in _emit_update_statements
    statement, multiparams
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/Users/Mark/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: ('mborysiak', 'My name is Kathy and I love dogs!', 3)] (Background on this error at: http://sqlalche.me/e/gkpj)
2019-03-29 20:50:43,727 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-03-29 20:50:56,196 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-03-31 20:09:07,851 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-03-31 20:09:18,760 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-03-31 20:57:14,043 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 19:02:54,280 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 19:08:39,599 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 19:09:53,131 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 19:13:26,051 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 19:31:24,668 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:03:45,665 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:26:20,579 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:32:37,522 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:33:16,778 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:36:00,270 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:39:58,447 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:41:03,504 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 20:42:16,441 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 21:03:57,184 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 21:04:34,945 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:43]
2019-04-01 21:42:35,960 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:45]
2019-04-01 21:46:38,176 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:45]
2019-04-01 21:51:50,434 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:45]
2019-04-01 21:52:10,928 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:45]
2019-04-03 19:54:38,751 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:45]
2019-04-03 19:55:44,957 INFO: Microblog startup [in /Users/Mark/Documents/GitHub/Flasky/app/__init__.py:45]
